# test_gemini_images.py - Test Gemini image generation with new API key
import google.generativeai as genai
from PIL import Image
from io import BytesIO
import os

def test_gemini_images():
    """Test Gemini image generation with the new API key"""
    print("Testing Gemini image generation with new API key...")
    
    # Configure with new API key
    genai.configure(api_key="AIzaSyD9Lu0X_gjIaBPnEuJ7o3WqPoXFJI4jwQs")
    
    try:
        # Try different Gemini models for image generation
        models_to_try = [
            'gemini-2.5-flash-image',
            'gemini-2.5-flash',
            'gemini-1.5-flash',
            'gemini-1.5-pro'
        ]
        
        for model_name in models_to_try:
            print(f"\nTrying model: {model_name}")
            try:
                model = genai.GenerativeModel(model_name)
                
                # Test prompt
                prompt = "Create a professional news photography image of a modern data center with dramatic lighting, high contrast, cinematic composition, photorealistic style, no text in the image"
                
                response = model.generate_content(prompt)
                
                # Check if response contains image data
                if hasattr(response, 'candidates') and response.candidates:
                    for part in response.candidates[0].content.parts:
                        if hasattr(part, 'inline_data') and part.inline_data:
                            # Save image
                            image_data = part.inline_data.data
                            image_path = f"gemini_test_{model_name.replace('-', '_')}.jpg"
                            
                            with open(image_path, 'wb') as f:
                                f.write(image_data)
                            
                            # Check image properties
                            with Image.open(image_path) as img:
                                print(f"SUCCESS: {model_name} generated image!")
                                print(f"Image size: {img.size}")
                                print(f"Image mode: {img.mode}")
                                print(f"File size: {os.path.getsize(image_path)} bytes")
                                print(f"Image saved as: {image_path}")
                                return True
                        elif hasattr(part, 'text') and part.text:
                            print(f"Text response from {model_name}: {part.text[:100]}...")
                
                print(f"No image generated by {model_name}")
                
            except Exception as e:
                print(f"Error with {model_name}: {e}")
                continue
        
        print("\nNo working image generation found")
        return False
        
    except Exception as e:
        print(f"Error testing Gemini images: {e}")
        return False

if __name__ == "__main__":
    test_gemini_images()



